name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
    - name: Build and push Docker images 
      uses: docker/build-push-action@v2.7.0
      with: 
        context: .
        file: .
        push: true
        tags: |
          gustavomartins09/digital_menu:latest
          gustavomartins09/digital_menu-mongodb:latest
        